var http = require('http');
var url = require('url');
var axios = require('axios');
var fs = require('fs');


function genOcorrencias(ocorrencias) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <title>Lista de Ocorrências</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-blue">
                    <h1>Lista de Ocorrências</h1>
                </header>
                
                <div class="w3-container">
                    <table class="w3-table w3-striped">
                        <tr>
                            <th>Identificador</th>
                            <th>Data</th>
                            <th>Animal</th>
                        </tr>
    `;
    ocorrencias.forEach(ocorr => {
        pagHTML += `
        <tr>
            <td>${ocorr.id}</td>
            <td>${ocorr.bite_date}</td>
            <td>${ocorr.SpeciesIDDesc}</td>
        </tr>
        `;
    });
    pagHTML += `
    </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024</h5>
                </footer>
        </div>
    </body>
</html>
    `;
    return pagHTML;
}

http.createServer((req, res) => {
    console.log(req.method + " " + req.url);
    if (req.url == '/') {
        fs.readFile("pagina1.html", (erro, dados) => {
            res.writeHead(200, { 'Content-type': 'text/html' });
            res.write(dados);
            res.end();
        });
    } else if (req.url == '/w3.css') {
        fs.readFile("w3.css", (erro, dados) => {
            res.writeHead(200, { 'Content-type': 'text/css' });
            res.write(dados);
            res.end();
        });
    
    } else if (req.url == '/animais') {
        axios.get("http://localhost:3000/ocorrencias") //Podemos fazer queries aqui
            .then(resp => {
                console.log(resp);
                res.writeHead(200, { 'Content-type': 'text/html', 'charset': 'utf-8' });
                html=genOcorrencias(resp.data)
                res.write(html);
                res.end();
            })
            .catch(erro => {
                res.writeHead(500, { 'Content-type': 'text/html', 'charset': 'utf-8' });
                res.write("<p>Ocorreu um erro: " + erro + "</p>");
                res.end();
            });

    } else if (req.url == '/animaisJSON') {
        axios.get("http://localhost:3000/ocorrencias")
            .then(resp => {
                console.log(resp);
                res.writeHead(200, { 'Content-type': 'text/json', 'charset': 'utf-8' });
                res.write(JSON.stringify(resp.data));
                res.end();
            })
            .catch(erro => {
                res.writeHead(500, { 'Content-type': 'text/html', 'charset': 'utf-8' });
                res.write("<p>Ocorreu um erro: " + erro + "</p>");
                res.end();
            });
    } else {
        res.writeHead(400, { 'Content-type': 'text/html', 'charset': 'utf-8' });
        res.write("<pre>Erro: Pedido não suportado</pre>");
        res.write("<pre>" + req.url + "</pre>");
        res.end();
    }
}).listen(2702);

console.log("Servidor à escuta na porta 2702");
